"""Publish the EngSVG dataset to a Hugging Face dataset repository.

Writes a dataset card, then uploads the shards. Publishing is not reversible in the way a local
write is --- once a repository is public it can be cloned and indexed even if deleted later --- so
this refuses to run without an explicit repository id, and creates private repositories unless
--public is passed.
"""
from __future__ import annotations
import argparse
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data/engsvg-dataset-factory-v2'

CARD = """---
license: {license}
task_categories:
- text-generation
- image-to-text
tags:
- engineering
- svg
- vector-graphics
- cad
- finite-element
- synthetic
size_categories:
- 100K<n<1M
configs:
- config_name: default
  data_files:
  - split: train
    path: tasks-*.jsonl.gz
---

# EngSVG: engineering drawings with solver-verified ground truth

{tasks:,} tasks over {designs:,} procedurally generated 2D engineering designs, each drawing
verified by a solver before it was allowed into the dataset.

## What makes it unusual

Every design is **certified before use**. Trusses are solved with a linear axial finite-element
method and admitted only when the equilibrium residual falls below 1e-5; plates pass manufacturing
geometry checks. {verified:,} of {designs:,} designs carry a passing record, and all {svg_targets:,}
SVG targets resolve to a verified asset. A drawing can also be recovered from its own SVG and
re-solved, so a model's output can be checked on physics rather than on pixel or token similarity.

## Composition

| task | rows | target |
|---|---:|---|
{task_table}

Families: {families}.

Splits are grouped by `lineage_id`, so every request derived from one design stays in one split.
Overlap between train, validation and test is zero, as is overlap with {excluded:,} hashes excluded
from an earlier release.

## Row format

Task shards (`tasks-*.jsonl.gz`) carry `prompt`, `target`, `task`, `family`, `split`, `lineage_id`,
`target_format`, `prompt_contains_svg`, `target_contains_svg` and `target_verification`. Asset shards
(`assets-*.jsonl.gz`) hold each design once: its IR model, three SVG style variants and the
verification record. `sample-gallery.html` opens the sample drawings in a browser.

## Honest limits

This is **synthetic** data: {n_families} families covering named parallel-chord bridge trusses
(Pratt, Howe, Warren and K-truss at several panel counts), two smaller fan trusses and two hole
patterns, varied by dimensions, loads and sections. Structures run from {min_members} to
{max_members} members. It is not a corpus of real engineering drawings, and no external CAD dataset
was used. Everything is planar: no 3D solids, curved surfaces, assemblies,
tolerances, GD&T, section views or title-block convention. Plate verification is geometric rather
than a stress solve. A model scoring well here has learned this generator, which is not the same as
having learned engineering drafting.

## Provenance

Generated by `engsvg_dataset_factory.py` at seed {seed}, deterministic and regenerable. A SHA-256
manifest is included.
"""


def card(summary, license_id):
    counts = summary['task_counts']
    fmt = {'text_to_svg': 'SVG', 'svg_edit': 'SVG', 'svg_to_ir': 'JSON', 'edit_action': 'JSON',
           'constraint_edit': 'JSON', 'engineering_analysis': 'JSON', 'clarify': 'JSON',
           'reject': 'JSON'}
    rows = '\n'.join(f'| `{k}` | {v:,} | {fmt.get(k, "JSON")} |'
                     for k, v in sorted(counts.items(), key=lambda kv: -kv[1]))
    return CARD.format(
        license=license_id, tasks=summary['tasks'], designs=summary['designs'],
        verified=summary['physics_or_geometry_verified'],
        svg_targets=summary['rows_with_full_svg_target'], task_table=rows,
        families=', '.join(f'`{k}`' for k in sorted(summary['family_counts'])),
        n_families=len(summary['family_counts']),
        min_members=summary.get('member_range', [7, 57])[0],
        max_members=summary.get('member_range', [7, 57])[1],
        excluded=summary.get('excluded_hashes', 0), seed=summary['seed'])


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--repo', required=True, help='e.g. username/engsvg-dataset')
    p.add_argument('--data', type=Path, default=DATA)
    p.add_argument('--token', default=os.environ.get('HF_TOKEN'))
    p.add_argument('--public', action='store_true', help='create a public repo; default is private')
    p.add_argument('--license', default='cc-by-4.0')
    p.add_argument('--dry-run', action='store_true', help='write the card and list files, upload nothing')
    a = p.parse_args()
    if '/' not in a.repo:
        raise SystemExit('repo must be <user-or-org>/<name>')
    summary = json.loads((a.data / 'dataset-summary.json').read_text())
    text = card(summary, a.license)
    (a.data / 'README.md').write_text(text)
    files = sorted(f for f in a.data.iterdir() if f.is_file())
    total = sum(f.stat().st_size for f in files)
    print(f'repo      {a.repo}   visibility {"PUBLIC" if a.public else "private"}')
    print(f'files     {len(files)}   total {total / 1e6:.1f} MB')
    print(f'card      {len(text)} chars written to {a.data / "README.md"}')
    if a.dry_run:
        print('\ndry run: nothing uploaded')
        return
    if not a.token:
        raise SystemExit('no token: pass --token or set HF_TOKEN')
    from huggingface_hub import HfApi
    api = HfApi(token=a.token)
    api.create_repo(a.repo, repo_type='dataset', private=not a.public, exist_ok=True)
    api.upload_folder(folder_path=str(a.data), repo_id=a.repo, repo_type='dataset',
                      commit_message='EngSVG: solver-verified engineering drawing tasks')
    print(f'\nuploaded -> https://huggingface.co/datasets/{a.repo}')


if __name__ == '__main__':
    main()
